"""empty message

Revision ID: cb9c233eea05
Revises: 04ef75b50778
Create Date: 2016-01-20 19:48:48.167030

"""

# revision identifiers, used by Alembic.
revision = 'cb9c233eea05'
down_revision = '04ef75b50778'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('nb_public', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'nb_public')
    ### end Alembic commands ###
